# Generated by Django 5.2.15 on 2026-06-18 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dossier',
        ),
    ]
