# Generated by Django 5.2.15 on 2026-06-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='traite',
            field=models.BooleanField(default=False, help_text='Indique si le dossier est traité (Traité / Non Traité)'),
        ),
    ]
