# Generated by Django 5.2.15 on 2026-06-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_secteur', models.CharField(max_length=100)),
                ('form_nom', models.CharField(max_length=100)),
                ('reg_key', models.IntegerField()),
                ('anciennete_annees', models.IntegerField()),
                ('emp_effectif', models.IntegerField()),
                ('emp_stop_co', models.CharField(max_length=10)),
                ('activity_status', models.CharField(max_length=50)),
                ('has_declaration', models.BooleanField(default=False)),
                ('has_payment', models.BooleanField(default=False)),
                ('montant_dette_total', models.FloatField(default=0)),
                ('score_global', models.FloatField()),
                ('niveau_risque', models.CharField(max_length=50)),
                ('score_employeur', models.FloatField()),
                ('score_declaration', models.FloatField()),
                ('score_recouvrement', models.FloatField()),
                ('score_controle', models.FloatField()),
                ('score_protocole', models.FloatField()),
                ('regles_declenchees', models.TextField(blank=True, null=True)),
                ('nb_regles', models.IntegerField(default=0)),
                ('top_feature_1', models.CharField(blank=True, max_length=255)),
                ('top_feature_2', models.CharField(blank=True, max_length=255)),
                ('top_feature_3', models.CharField(blank=True, max_length=255)),
                ('recommandation_1', models.TextField(blank=True)),
                ('score_anomalie', models.FloatField()),
                ('niveau_anomalie', models.CharField(max_length=50)),
                ('is_outlier_iforest', models.BooleanField(default=False)),
                ('anomalie_top_1', models.CharField(blank=True, max_length=255)),
                ('anomalie_top_2', models.CharField(blank=True, max_length=255)),
                ('anomalie_top_3', models.CharField(blank=True, max_length=255)),
                ('recommandation_2', models.TextField(blank=True)),
                ('quadrant', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('progress', 'En cours'), ('closed', 'Clôturé')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
