# Generated by Django 5.2.15 on 2026-06-19 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0002_delete_dossier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_emp_hash', models.CharField(db_index=True, help_text="ID unique hashé de l'employeur", max_length=255, unique=True)),
                ('forme_nom', models.CharField(help_text='Raison sociale (FORME_NOM)', max_length=255)),
                ('emp_secteur', models.CharField(help_text="Secteur d'activité (EMP_SECTEUR)", max_length=150)),
                ('reg_key', models.CharField(help_text='Code région (REG_KEY)', max_length=50)),
                ('anciennete_annees', models.PositiveIntegerField(default=0, help_text='Ancienneté en années')),
                ('emp_effectif', models.PositiveIntegerField(default=0, help_text="Effectif d'employés (EMP_EFFECTIF)")),
                ('emp_stop_co', models.BooleanField(default=False, help_text='Cotisation stoppée (EMP_STOP_CO)')),
                ('activity_status', models.CharField(default='ACTIF', help_text='Statut activité (ACTIVITY_STATUS)', max_length=50)),
                ('has_declaration', models.BooleanField(default=True)),
                ('has_payment', models.BooleanField(default=True)),
                ('montant_dette_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('flag_fraude_confirmee_ever', models.BooleanField(default=False, help_text='Flag fraude confirmée historique')),
                ('flag_non_respect_ever', models.BooleanField(default=False, help_text='Flag non-conformité historique')),
                ('flag_redressement_ever', models.BooleanField(default=False, help_text='Flag redressement historique')),
                ('score_global', models.FloatField(default=0.0, help_text='Score global composite [0-1]')),
                ('niveau_risque', models.CharField(default='FAIBLE', max_length=20)),
                ('score_employeur', models.FloatField(default=0.0)),
                ('score_declaration', models.FloatField(default=0.0)),
                ('score_recouvrement', models.FloatField(default=0.0)),
                ('score_controle', models.FloatField(default=0.0)),
                ('score_protocole', models.FloatField(default=0.0)),
                ('regles_declenchees', models.JSONField(blank=True, default=list)),
                ('nb_regles', models.PositiveIntegerField(default=0)),
                ('interactions_detectees', models.JSONField(blank=True, default=dict)),
                ('nb_interactions', models.PositiveIntegerField(default=0, help_text="Nombre d'interactions détectées")),
                ('top_feature_1', models.CharField(blank=True, max_length=100, null=True)),
                ('top_feature_2', models.CharField(blank=True, max_length=100, null=True)),
                ('top_feature_3', models.CharField(blank=True, max_length=100, null=True)),
                ('recommandation_1', models.TextField(blank=True, null=True)),
                ('score_anomalie', models.FloatField(default=0.0)),
                ('niveau_anomalie', models.CharField(default='NORMAL', max_length=50)),
                ('is_outlier_iforest', models.BooleanField(default=False)),
                ('anomalie_top_1', models.CharField(blank=True, max_length=150, null=True)),
                ('anomalie_top_2', models.CharField(blank=True, max_length=150, null=True)),
                ('anomalie_top_3', models.CharField(blank=True, max_length=150, null=True)),
                ('recommandation_2', models.TextField(blank=True, null=True)),
                ('quadrant', models.CharField(default='Q4_LOW_RISK_LOW_ANOMALY', max_length=50)),
                ('statut', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours de traitement'), ('SUSPENDU', 'Suspendu / En attente'), ('CLOTURE', 'Clôturé')], default='NOUVEAU', max_length=20)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='MOYENNE', max_length=20)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('inspecteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_assignes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score_global'],
                'indexes': [models.Index(fields=['id_emp_hash'], name='dossiers_do_id_emp__782157_idx'), models.Index(fields=['score_global'], name='dossiers_do_score_g_1de2b3_idx'), models.Index(fields=['statut'], name='dossiers_do_statut_d0dd4d_idx'), models.Index(fields=['quadrant'], name='dossiers_do_quadran_e3b4e6_idx')],
            },
        ),
    ]
