# Generated by Django 5.2.15 on 2026-06-19 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(help_text='Texte du commentaire')),
                ('type_commentaire', models.CharField(choices=[('OBSERVATION', 'Observation'), ('ALERTE', 'Alerte'), ('DECISION', 'Décision')], default='OBSERVATION', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_interne', models.BooleanField(default=True, help_text='Visibilité interne uniquement')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='dossiers.dossier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
