# Generated by Django 5.2.15 on 2026-06-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Indique si la notification a été lue (applicable pour ALERTE)'),
        ),
        migrations.AddField(
            model_name='comment',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
