# Generated by Django 5.2.15 on 2026-06-19 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(max_length=50)),
                ('nouveau_statut', models.CharField(max_length=50)),
                ('commentaire', models.TextField(blank=True, help_text='Justification du changement de statut', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_workflow', to='dossiers.dossier')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
