# Generated by Django 5.2.15 on 2026-06-19 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('INSPECTEUR', 'Inspecteur'), ('DIRECTEUR', 'Directeur'), ('ADMIN', 'Administrateur')], default='INSPECTEUR', max_length=20)),
                ('region', models.CharField(blank=True, help_text="Région CNSS d'affectation", max_length=100, null=True)),
                ('service', models.CharField(blank=True, help_text='Service administratif', max_length=100, null=True)),
                ('badge_id', models.CharField(blank=True, help_text='Numéro de carte professionnelle', max_length=50, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
